# Generated by Django 4.1.4 on 2022-12-21 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expiredpayment',
            name='payment_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='e_p_u', to='v2.paymentuser'),
        ),
        migrations.AlterField(
            model_name='paymentuser',
            name='payment_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(choices=[('YT', 'Youtube'), ('SP', 'Spotify'), ('NF', 'Netflix'), ('AP', 'Amazon Video'), ('ST', 'Start+'), ('PM', 'Paramount+')], default='NF', max_length=2),
        ),
    ]
